# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html

manifest:
  
  remotes:
    - name: nxpmicro
      url-base: https://github.com/NXPmicro

  defaults:
    remote: nxpmicro

  projects:
    - name: mcux-sdk-examples
      revision: b58d7a0c2dba35c2158e0614917a8cefe7f75c90
      path: examples
    - name: FreeRTOS-Kernel
      revision: MCUX_2.10.0
      path: rtos/freertos/freertos_kernel
    - name: mcux-sdk-middleware-sdmmc
      revision: MCUX_2.10.0
      path: middleware/sdmmc
    - name: mcux-sdk-middleware-multicore
      path: middleware/multicore
      revision: 50d7e6bd2e0501aad2944abe4eaf616fd465fb8e
    - name: rpmsg-lite
      path: middleware/multicore/rpmsg_lite
      url:  https://github.com/NXPmicro/rpmsg-lite
      revision: d203ade3010a5e79ecb9aab50aa1c1af707efaa6
    - name: erpc
      path: middleware/multicore/erpc
      url:  https://github.com/EmbeddedRPC/erpc
      revision: 1.9.0
    - name: mcux-soc-svd
      revision: 4043d9ec3b173a0c45212e5536e0e8352a8634b5
      path: svd
    - name: fatfs
      path: middleware/fatfs
      revision: MCUX_2.10.0
    - name: mcux-sdk-middleware-eiq
      revision: MCUX_2.10.0
      path: middleware/eiq
    - name: mcux-sdk-middleware-deepviewrt
      revision: MCUX_2.10.0
      path: middleware/eiq/deepviewrt
    - name: mcux-sdk-middleware-glow
      revision: MCUX_2.10.0
      path: middleware/eiq/glow
    - name: mcux-sdk-middleware-tensorflow
      revision: MCUX_2.10.0
      path: middleware/eiq/tensorflow-lite
    - name: mcux-sdk-middleware-usb
      url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-usb.git
      path: middleware/usb
      revision: 648341d833a048c7982d129e687e5a5e2fad19c0
    - name: mcux-sdk-middleware-edgefast-bluetooth
      url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-edgefast-bluetooth.git
      path: middleware/edgefast_bluetooth
      revision: a32e7204a94c781d19aa76025ccd0fc74acb1ad6
    - name: mcux-sdk-middleware-ethermind
      url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-ethermind.git
      path: middleware/wireless/ethermind
      revision: 071e496040723aaa69e0d5e0324a08296fad5c51
    - name: mcux-azure-rtos
      url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-azure-rtos.git
      path: rtos/azure-rtos
      revision: MCUX_2.11.0
    - name: threadx
      url: ssh://git@bitbucket.sw.nxp.com/dnind/threadx.git
      path: rtos/azure-rtos/threadx
      revision: MCUX_2.11.0
    - name: filex
      url: ssh://git@bitbucket.sw.nxp.com/dnind/filex.git
      path: rtos/azure-rtos/filex
      revision: MCUX_2.11.0
    - name: levelx
      url: ssh://git@bitbucket.sw.nxp.com/dnind/levelx.git
      path: rtos/azure-rtos/levelx
      revision: MCUX_2.11.0
    - name: netxduo
      url: ssh://git@bitbucket.sw.nxp.com/dnind/netxduo.git
      path: rtos/azure-rtos/netxduo
      revision: MCUX_2.11.0
    - name: usbx
      url: ssh://git@bitbucket.sw.nxp.com/dnind/usbx.git
      path: rtos/azure-rtos/usbx
      revision: MCUX_2.11.0
    - name: guix
      url: ssh://git@bitbucket.sw.nxp.com/dnind/guix.git
      path: rtos/azure-rtos/guix
      revision: MCUX_2.11.0
  self:
    path: core
