manifest:
  remotes:
  - name: nxpmicro
    url-base: git@bitbucket.sw.nxp.com:mcucore
  defaults:
    remote: nxpmicro
  projects:
  - name: mcux-sdk-examples-github.git
    revision: 96976374bba2e76bcd11817f8738248d9317039a
    path: examples
  - name: freertos-kernel.git
    revision: 5f449f6510831674e9867f9a61e29eecbedfdc1c
    path: rtos/freertos/freertos_kernel
  - name: mcux-sdk-sdmmc.git
    revision: 10968f0de222281b757aab26d210c2ce34175dbb
    path: middleware/sdmmc
  - name: mcux-sdk-multicore.git
    path: middleware/multicore
    revision: 507289ca9ec55e3e016f17bfcd3ebc010f4f34ce
  - name: rpmsg-lite
    path: middleware/multicore/rpmsg_lite
    url: https://github.com/NXPmicro/rpmsg-lite
    revision: 3933134378690a9c04d533e26516b3388fe4acc3
  - name: erpc
    path: middleware/multicore/erpc
    url: https://github.com/EmbeddedRPC/erpc
    revision: ab306fc1a64e12769ee52819b85189374e639588
  self:
    path: core
