manifest:
  remotes:
  - name: nxpmicro
    url-base: https://github.com/NXPmicro
  defaults:
    remote: nxpmicro
  projects:
  - name: mcux-sdk-examples
    revision: 57d4942cdfccc6f4380a6bc43072dab2ced2b12a
    path: examples
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-examples-github.git
  - name: FreeRTOS-Kernel
    revision: 369b19c903026908ffb44431b91083055a740da9
    path: rtos/freertos/freertos_kernel
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/freertos-kernel.git
  - name: mcux-sdk-middleware-sdmmc
    revision: 92d79a983ee23bcb1a17bca151eb6c2030964cf0
    path: middleware/sdmmc
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-sdmmc.git
  - name: mcux-sdk-middleware-multicore
    path: middleware/multicore
    revision: 49963441f277fdbbc6a9e1d8763785473742b855
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-multicore.git
  - name: rpmsg-lite
    path: middleware/multicore/rpmsg_lite
    url: https://github.com/NXPmicro/rpmsg-lite
    revision: f12ffe998a9b52f0327e109b5b3005a2ef787770
  - name: erpc
    path: middleware/multicore/erpc
    url: https://github.com/EmbeddedRPC/erpc
    revision: 6a571caf6d5042af5d63ff8745f2e4b24e14bc9f
  - name: lwip
    path: middleware/lwip
    revision: 5b7886c24cff9f87d4f1ed5c677cfa275a957497
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/lwip.git
  - name: mbedtls
    path: middleware/mbedtls
    revision: ca0ed0548b102eb669d0f920a2de36864e50821c
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-mbedtls.git
  self:
    path: core
