manifest:
  remotes:
  - name: nxpmicro
    url-base: git@bitbucket.sw.nxp.com:mcucore
  defaults:
    remote: nxpmicro
  projects:
  - name: mcux-sdk-examples-github.git
    revision: 30d2a5ad7d8054593751ff44de929883c92c6844
    path: examples
  - name: freertos-kernel.git
    revision: 2d417b08798756c7f1ca12fc1a399aed91c15562
    path: rtos/freertos/freertos_kernel
  - name: mcux-sdk-sdmmc.git
    revision: b33d5824e7278318cd2e0fe961132c89f8c4cb38
    path: middleware/sdmmc
  - name: mcux-sdk-multicore.git
    path: middleware/multicore
    revision: MCUX_2.11.0
  - name: rpmsg-lite
    path: middleware/multicore/rpmsg_lite
    url: https://github.com/NXPmicro/rpmsg-lite
    revision: v3.2.0
  - name: erpc
    path: middleware/multicore/erpc
    url: https://github.com/EmbeddedRPC/erpc
    revision: 1.9.0
  - name: mcux-soc-svd.git
    revision: 25f39a20a2811cff867863897393967b5a4d5635
    path: svd
  - name: mcux-sdk-fatfs.git
    path: middleware/fatfs
    revision: 46c842a9ecf8683043c156a92f600fba22663328
  - name: mcux-sdk-eiq.git
    revision: 8ac0c8494e59c3033fe6470ee45885478513d14e
    path: middleware/eiq
  - name: mcux-sdk-deepviewrt.git
    revision: MCUX_2.11.0
    path: middleware/eiq/deepviewrt
  - name: mcux-sdk-glow.git
    revision: 32cde8de0c97efaed1a2a28d756f10c78afceee4
    path: middleware/eiq/glow
  - name: mcux-sdk-tensorflow.git
    revision: f06d4c0183e64be8624ea0e9ea21a350d3d4228b
    path: middleware/eiq/tensorflow-lite
  - name: mcux-sdk-middleware-usb
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-usb.git
    path: middleware/usb
    revision: MCUX_2.11.0
  - name: mcux-sdk-middleware-edgefast-bluetooth
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-edgefast-bluetooth.git
    path: middleware/edgefast_bluetooth
    revision: MCUX_2.11.0
  - name: mcux-sdk-middleware-ethermind
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-ethermind.git
    path: middleware/wireless/ethermind
    revision: MCUX_2.11.0
  - name: mcux-azure-rtos
    url: ssh://git@bitbucket.sw.nxp.com/mcucore/mcux-sdk-azure-rtos.git
    path: rtos/azure-rtos
    revision: MCUX_2.11.0
  - name: threadx
    url: ssh://git@bitbucket.sw.nxp.com/dnind/threadx.git
    path: rtos/azure-rtos/threadx
    revision: MCUX_2.11.0
  - name: filex
    url: ssh://git@bitbucket.sw.nxp.com/dnind/filex.git
    path: rtos/azure-rtos/filex
    revision: MCUX_2.11.0
  - name: levelx
    url: ssh://git@bitbucket.sw.nxp.com/dnind/levelx.git
    path: rtos/azure-rtos/levelx
    revision: MCUX_2.11.0
  - name: netxduo
    url: ssh://git@bitbucket.sw.nxp.com/dnind/netxduo.git
    path: rtos/azure-rtos/netxduo
    revision: MCUX_2.11.0
  - name: usbx
    url: ssh://git@bitbucket.sw.nxp.com/dnind/usbx.git
    path: rtos/azure-rtos/usbx
    revision: MCUX_2.11.0
  - name: guix
    url: ssh://git@bitbucket.sw.nxp.com/dnind/guix.git
    path: rtos/azure-rtos/guix
    revision: MCUX_2.11.0
  self:
    path: core
